[soc_controller]
soc-admin ansible_connection=local

[ids_hosts]
ids-management ansible_host=192.168.20.148 ansible_user=ids-management

[wazuh_manager]
soc-admin ansible_connection=local

[splunk_searchhead]
soc-admin ansible_connection=local

[zeek_manager]
ids-management ansible_host=192.168.20.148 ansible_user=ids-management

[suricata_manager]
ids-management ansible_host=192.168.20.148 ansible_user=ids-management
