all:
  hosts:
    soc-admin:
      ansible_connection: local
      ansible_user: soc-admin

    ids-management:
      ansible_host: 192.168.20.148
      ansible_user: ids-management

    splunk:
      ansible_host: 192.168.122.181
      ansible_user: splunk
