---
- name: Deploy APTPACK Command and Control / Collection phase
  hosts: soc-admin
  gather_facts: true
  vars_files:
    - ../group_vars/all.yml
  vars:
    aptpack_phase_code: CA
    aptpack_phase_dir_name: APTPACK-CA
  roles:
    - role: aptpack_phase_deploy
