---
- name: Deploy APTPACK Discovery phase
  hosts: soc-admin
  gather_facts: true
  vars_files:
    - ../group_vars/all.yml
  vars:
    aptpack_phase_code: DISC
    aptpack_phase_dir_name: APTPACK-DISC
  roles:
    - role: aptpack_phase_deploy
