---
- name: Deploy APTPACK Initial Access phase
  hosts: soc-admin
  gather_facts: true
  vars_files:
    - ../group_vars/all.yml
  vars:
    aptpack_phase_code: IA
    aptpack_phase_dir_name: APTPACK-IA
  roles:
    - role: aptpack_phase_deploy
