---
- name: Deploy APTPACK Execution phase
  hosts: soc-admin
  gather_facts: true
  vars_files:
    - ../group_vars/all.yml
  vars:
    aptpack_phase_code: EXEC
    aptpack_phase_dir_name: APTPACK-EXEC
  roles:
    - role: aptpack_phase_deploy
