---
- name: Deploy APTPACK Persistence and Privilege Escalation phase
  hosts: soc-admin
  gather_facts: true
  vars_files:
    - ../group_vars/all.yml
  vars:
    aptpack_phase_code: PE
    aptpack_phase_dir_name: APTPACK-PE
  roles:
    - role: aptpack_phase_deploy
